[build]
  command = "hugo && npx netlify-lambda build src/functions"
  publish = "public"
  functions = "functions"

[context.production]
  command = "hugo && npx netlify-lambda build src/functions"
  functions = "functions"
  [context.production.environment]
    HUGO_VERSION = "0.41"
    HUGO_ENV = "production"